ynct-d-members/todo-team

package.json, yarn.lock
=> chore: split dev

api/routes.ts, api/server.ts, package-lock.json, package.json
1. /apiにfastifyのためのファイルを追加
2. 次のパッケージを追加: fastify, npm-run-all
3. `npm run start`でreactとfastifyサーバが起動するように変更
close #8
=> Joint client server

.vscode/extensions.json, .vscode/settings.json
拡張子の設定と、保存時にformatterがかかるように設定した
close #9
=> VSCodeの設定追加

.gitignore
eslintのキャッシュファイルを.gitignoreに追加しました
=> added .eslintcache to .gitignore

api/server.ts, package-lock.json, package.json, tsconfig.json
server.tsでimport Fastifyをすると怒られていたので，tsconfig.jsonにてmoduleプロパティを変更しつつ，server.tsをts-nodeで実行するように変更した
=> Fastifyをts-nodeで動かせるようにした

api/server.ts, package-lock.json, package.json
/todo/:idにアクセスすると，:idに対応するTodoを返却する．
現在は:id === 1としてアクセスすると，/src/pages/todos/todo-mock.tsのtodos[0]をそのまま返すようにしている．
=> Todoapi get

api/server.ts, package-lock.json, package.json
Fastifyにてcors対策を行った．
localhostからの通信は許可し，それ以外の通信は遮断するようにした．
=> Cors setting

api/server.ts
APIサーバの/todo/にアクセスするとTodo一覧を返すようにした．
現在はモックなので`src/pages/todos/todo-mock.ts`から値を返している．
Close #37
=> feat: added /todo/ endpoint for get TodosList

src/pages/todos/todo-detail/containers/todo-detail.container.tsx, src/pages/todos/todo-list/components/index.ts, src/pages/todos/todo-list/components/todo-list.component.tsx, src/pages/todos/todo-list/containers/index.ts, src/pages/todos/todo-list/containers/todo-list.container.tsx, src/pages/todos/todo-list/index.ts, src/pages/todos/todo-list/todo-list.page.tsx, src/pages/todos/todo.route.tsx, src/pages/todos/todo.state.ts
TodoListの作成
こんな感じになった。
リンクをクリックするとdetailに移行する。
detailでもgetしてるから無駄感がすごいけど、storeでfetchしたやつを管理すればよくなる。
closes #44
=> TodoListの作成

src/App.test.tsx, src/pages/todos/todo-detail/components/__snapshots__/todo-detail.cpmponent.test.tsx.snap, src/pages/todos/todo-detail/components/todo-detail.cpmponent.test.tsx, src/pages/todos/todo-detail/containers/todo-detail.container.tsx, src/pages/todos/todo-detail/index.ts, src/pages/todos/todo-detail/todo-detail.page.tsx, src/pages/todos/todo-list/components/index.ts, src/pages/todos/todo-list/components/todo-list.component.tsx, src/pages/todos/todo-list/containers/index.ts, src/pages/todos/todo-list/containers/todo-list.container.tsx, src/pages/todos/todo-list/index.ts, src/pages/todos/todo-list/todo-list.page.tsx, src/pages/todos/todo.route.tsx, src/pages/todos/todo.state.ts
PageComponentの追加
listからdetailに遷移するさいにparamにidを付与することで、うまいことできる。
独り言
listを作ってから入れるべきだったな、と後悔している。
closes #47
=> Create todo detail page component

package-lock.json, package.json, src/pages/todos/todo-create/components/__snapshots__/todo-create.component.spec.tsx.snap, src/pages/todos/todo-create/components/index.ts, src/pages/todos/todo-create/components/todo-create.component.spec.tsx, src/pages/todos/todo-create/components/todo-create.component.tsx, src/pages/todos/todo-create/containers/index.ts, src/pages/todos/todo-create/containers/todo-create.container.tsx, src/pages/todos/todo-create/index.ts, src/pages/todos/todo-create/todo-create.page.tsx, src/pages/todos/todo.route.tsx
react-hook-formの追加
todos/newのpathを追加
formを作ったけど、console.logにしか出力はしないやつ
=> Todo create

api/modules/todo/index.ts, api/router.ts
=> refactor: add todo barrel

.env.template, api/modules/todo/todo.controller.ts, api/modules/todo/todo.routes.ts, api/modules/todo/todo.service.ts, api/server.ts
/todos/update/:idに**PATCH**で`{ "title": "Todoのタイトル"}`を送ることでアップデートできるようにした
=> /todos/update/:idを追加

api/modules/todo/todo.controller.ts, api/server.ts
今まで: Controllerでreplyパケットを作るたびに`"Content-Type": "application/json"`を設定していた
これから: 共通化したのでControllerで↑を設定する必要がなくなる
=> feat: add header to all reply

src/pages/todos/todo-list/components/todo-list.component.tsx
（これはVSCodeで作ったPRです）
listのトップに新規作成のリンクを追加した
#closes #63
=> feat(pages/todos): listにcreateの導線を追加

api/modules/todo/todo.controller.ts, api/modules/todo/todo.routes.ts, api/modules/todo/todo.service.ts
=> feat: add delete route

prisma/migrations/20210219145353_add_todo_completed_column/migration.sql, prisma/schema.prisma, src/pages/todos/todo-detail/components/todo-detail.cpmponent.test.tsx
- schemaを修正
- migrationを実行
- testの型を一部修正
#72
=> Todoテーブルにcompletedカラムを追加

api/server.ts
フックの呼び出しタイミングを最適化した
(変なブランチからですまん)
=> feat: optimise hook

src/pages/todos/todo.state.ts
=> chore(todos): adjust todo state

.github/workflows/test.yml, api/modules/todo/prisma-test-environment.js, prisma/schema.prisma
=> ci: remove DATABASE_URL_WITH_NAME

docker-compose.yml
=> chore: change container timezone

package.json
[volta](https://volta.sh/)を使ってnodeとnpmのバージョン指定をしてみた。
asdfではnpmバージョンまでは指定できなかったのを解決できる
=> package: specify node/npm version via volta

src/App.test.tsx
=> test(App.test.tsx): remove test

README.md
=> docs(README.md): update about volta

prisma/schema.prisma
https://github.com/prisma/prisma/releases/tag/2.20.0
使い得っぽいオプションが生えてたので追加
=> chore(prisma): add npi options

src/pages/todos/todo-detail/components/todo-detail.component.tsx, src/pages/todos/todo-detail/containers/todo-detail.container.tsx, src/pages/todos/todo-detail/todo-detail.page.tsx, src/store/todo/actions/todo.action.ts, src/store/todo/facades/todo.facade.ts, src/store/todo/reducers/todo.reducer.ts, src/store/todo/selectors/todo.selector.ts, src/store/todo/states/todo.state.ts
いろいろ追加したよ
これで詳細画面にいったときにredux経由で取得ができるよ
=> Todo fetch

api/modules/todo/prisma-test-environment.js, api/modules/todo/todo.controller.ts, api/modules/todo/todo.service.test.ts, api/modules/todo/todo.service.ts, package-lock.json, package.json, tsconfig.json
=> Todo service

api/modules/todo/todo.controller.ts
TodoServiceのconstructorが動かない問題に対応
=> fix: re-declaration TodoService

config/webpack.config.js, tsconfig.json
path aliasの追加
これで `@/store` とかで読み込める
=> chore(*): path alias

package.json, src/pages/todos/todo-create/components/todo-create.component.spec.tsx, src/pages/todos/todo-create/containers/todo-create.container.tsx, src/pages/todos/todo-detail/components/todo-detail.component.test.tsx, src/pages/todos/todo-detail/components/todo-detail.component.tsx, src/pages/todos/todo-detail/containers/todo-detail.container.tsx, src/pages/todos/todo-list/containers/todo-list.container.tsx
=> Refactor path

src/libs/http/index.ts, src/pages/todos/todo-detail/components/__snapshots__/todo-detail.component.test.tsx.snap, src/pages/todos/todo-detail/components/todo-detail.component.test.tsx, src/pages/todos/todo-detail/components/todo-detail.component.tsx, src/pages/todos/todo-edit/components/index.ts, src/pages/todos/todo-edit/components/todo-edit.component.tsx, src/pages/todos/todo-edit/containers/index.ts, src/pages/todos/todo-edit/containers/todo-edit.container.tsx, src/pages/todos/todo-edit/index.ts, src/pages/todos/todo-edit/todo-edit.page.tsx, src/pages/todos/todo.route.tsx
=> Todo editの追加

api/modules/todo/todo.controller.ts, api/router.ts, api/server.ts
- コントローラーにデコレータを付けてルーターの代わりに使うようにした。
- それぞれのルートのリクエスト、レスポンスのスキーマを定義した
- 共通エラーレスポンスを定義した
=> fastify-decoratorを使うようにした

src/pages/todos/todo-detail/containers/todo-detail.container.tsx, src/pages/todos/todo-edit/containers/todo-edit.container.tsx
=> feat(*): update api path
